#include <deip/protocol/get_config.hpp>
#include <deip/protocol/config.hpp>
#include <deip/protocol/asset.hpp>
#include <deip/protocol/types.hpp>
#include <deip/protocol/version.hpp>

namespace deip {
namespace protocol {

fc::variant_object get_config()
{
    fc::mutable_variant_object result;

    // clang-format off

#ifdef IS_TEST_NET
    result[ "IS_TEST_NET" ] = true;
#else
    result[ "IS_TEST_NET" ] = false;
#endif

    // clang-format on

    result["deip_100_PERCENT"] = deip_100_PERCENT;
    result["deip_1_PERCENT"] = deip_1_PERCENT;
    result["deip_1_TENTH_PERCENT"] = deip_1_TENTH_PERCENT;
    result["deip_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = deip_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
    result["deip_ADDRESS_PREFIX"] = deip_ADDRESS_PREFIX;
    result["deip_APR_PERCENT_MULTIPLY_PER_BLOCK"] = deip_APR_PERCENT_MULTIPLY_PER_BLOCK;
    result["deip_APR_PERCENT_MULTIPLY_PER_HOUR"] = deip_APR_PERCENT_MULTIPLY_PER_HOUR;
    result["deip_APR_PERCENT_MULTIPLY_PER_ROUND"] = deip_APR_PERCENT_MULTIPLY_PER_ROUND;
    result["deip_APR_PERCENT_SHIFT_PER_BLOCK"] = deip_APR_PERCENT_SHIFT_PER_BLOCK;
    result["deip_APR_PERCENT_SHIFT_PER_HOUR"] = deip_APR_PERCENT_SHIFT_PER_HOUR;
    result["deip_APR_PERCENT_SHIFT_PER_ROUND"] = deip_APR_PERCENT_SHIFT_PER_ROUND;
    result["deip_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = deip_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
    result["deip_BANDWIDTH_PRECISION"] = deip_BANDWIDTH_PRECISION;
    result["deip_BLOCKCHAIN_HARDFORK_VERSION"] = deip_BLOCKCHAIN_HARDFORK_VERSION;
    result["deip_BLOCKCHAIN_VERSION"] = deip_BLOCKCHAIN_VERSION;
    result["deip_BLOCK_INTERVAL"] = deip_BLOCK_INTERVAL;
    result["deip_BLOCKS_PER_DAY"] = deip_BLOCKS_PER_DAY;
    result["deip_BLOCKS_PER_HOUR"] = deip_BLOCKS_PER_HOUR;
    result["deip_BLOCKS_PER_YEAR"] = deip_BLOCKS_PER_YEAR;
    result["deip_CASHOUT_WINDOW_SECONDS"] = deip_CASHOUT_WINDOW_SECONDS;
    result["deip_COMMENT_REWARD_FUND_NAME"] = deip_COMMENT_REWARD_FUND_NAME;
    result["deip_CONTENT_APR_PERCENT"] = deip_CONTENT_APR_PERCENT;
    result["deip_CONTENT_REWARD_PERCENT"] = deip_CONTENT_REWARD_PERCENT;
    result["deip_CREATE_ACCOUNT_DELEGATION_RATIO"] = deip_CREATE_ACCOUNT_DELEGATION_RATIO;
    result["deip_CREATE_ACCOUNT_DELEGATION_TIME"] = deip_CREATE_ACCOUNT_DELEGATION_TIME;
    result["deip_CREATE_ACCOUNT_WITH_deip_MODIFIER"] = deip_CREATE_ACCOUNT_WITH_deip_MODIFIER;
    result["deip_HARDFORK_REQUIRED_WITNESSES"] = deip_HARDFORK_REQUIRED_WITNESSES;
    result["deip_INFLATION_NARROWING_PERIOD"] = deip_INFLATION_NARROWING_PERIOD;
    result["deip_INFLATION_RATE_START_PERCENT"] = deip_INFLATION_RATE_START_PERCENT;
    result["deip_INFLATION_RATE_STOP_PERCENT"] = deip_INFLATION_RATE_STOP_PERCENT;
    result["deip_IRREVERSIBLE_THRESHOLD"] = deip_IRREVERSIBLE_THRESHOLD;
    result["deip_MAX_ACCOUNT_NAME_LENGTH"] = deip_MAX_ACCOUNT_NAME_LENGTH;
    result["deip_MAX_ACCOUNT_WITNESS_VOTES"] = deip_MAX_ACCOUNT_WITNESS_VOTES;
    result["deip_MAX_BLOCK_SIZE"] = deip_MAX_BLOCK_SIZE;
    result["deip_MAX_COMMENT_DEPTH"] = deip_MAX_COMMENT_DEPTH;
    result["deip_MAX_FEED_AGE_SECONDS"] = deip_MAX_FEED_AGE_SECONDS;
    result["deip_MAX_MEMO_SIZE"] = deip_MAX_MEMO_SIZE;
    result["deip_MAX_WITNESSES"] = deip_MAX_WITNESSES;
    result["deip_MAX_PERMLINK_LENGTH"] = deip_MAX_PERMLINK_LENGTH;
    result["deip_MAX_PROXY_RECURSION_DEPTH"] = deip_MAX_PROXY_RECURSION_DEPTH;
    result["deip_MAX_RESERVE_RATIO"] = deip_MAX_RESERVE_RATIO;
    result["deip_MAX_RUNNER_WITNESSES"] = deip_MAX_RUNNER_WITNESSES;
    result["deip_MAX_SHARE_SUPPLY"] = deip_MAX_SHARE_SUPPLY;
    result["deip_MAX_SIG_CHECK_DEPTH"] = deip_MAX_SIG_CHECK_DEPTH;
    result["deip_MAX_TIME_UNTIL_EXPIRATION"] = deip_MAX_TIME_UNTIL_EXPIRATION;
    result["deip_MAX_TRANSACTION_SIZE"] = deip_MAX_TRANSACTION_SIZE;
    result["deip_MAX_UNDO_HISTORY"] = deip_MAX_UNDO_HISTORY;
    result["deip_MAX_VOTE_CHANGES"] = deip_MAX_VOTE_CHANGES;
    result["deip_MAX_VOTED_WITNESSES"] = deip_MAX_VOTED_WITNESSES;
    result["deip_MAX_WITHDRAW_ROUTES"] = deip_MAX_WITHDRAW_ROUTES;
    result["deip_MAX_WITNESS_URL_LENGTH"] = deip_MAX_WITNESS_URL_LENGTH;
    result["deip_MIN_ACCOUNT_CREATION_FEE"] = deip_MIN_ACCOUNT_CREATION_FEE;
    result["deip_MIN_ACCOUNT_NAME_LENGTH"] = deip_MIN_ACCOUNT_NAME_LENGTH;
    result["deip_MIN_BLOCK_SIZE_LIMIT"] = deip_MIN_BLOCK_SIZE_LIMIT;
    result["deip_MIN_CONTENT_REWARD"] = deip_MIN_CONTENT_REWARD;
    result["deip_MIN_CURATE_REWARD"] = deip_MIN_CURATE_REWARD;
    result["deip_MIN_PERMLINK_LENGTH"] = deip_MIN_PERMLINK_LENGTH;
    result["deip_MIN_REPLY_INTERVAL"] = deip_MIN_REPLY_INTERVAL;
    result["deip_MIN_ROOT_COMMENT_INTERVAL"] = deip_MIN_ROOT_COMMENT_INTERVAL;
    result["deip_MIN_VOTE_INTERVAL_SEC"] = deip_MIN_VOTE_INTERVAL_SEC;
    result["deip_MIN_FEEDS"] = deip_MIN_FEEDS;
    result["deip_MINING_REWARD"] = deip_MINING_REWARD;
    result["deip_MIN_PAYOUT"] = deip_MIN_PAYOUT;
    result["deip_MIN_POW_REWARD"] = deip_MIN_POW_REWARD;
    result["deip_MIN_PRODUCER_REWARD"] = deip_MIN_PRODUCER_REWARD;
    result["deip_MIN_TRANSACTION_EXPIRATION_LIMIT"] = deip_MIN_TRANSACTION_EXPIRATION_LIMIT;
    result["deip_MIN_UNDO_HISTORY"] = deip_MIN_UNDO_HISTORY;
    result["deip_NUM_INIT_DELEGATES"] = deip_NUM_INIT_DELEGATES;
    result["deip_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = deip_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
    result["deip_OWNER_AUTH_RECOVERY_PERIOD"] = deip_OWNER_AUTH_RECOVERY_PERIOD;
    result["deip_OWNER_UPDATE_LIMIT"] = deip_OWNER_UPDATE_LIMIT;
    result["deip_POST_REWARD_FUND_NAME"] = deip_POST_REWARD_FUND_NAME;
    result["deip_POW_APR_PERCENT"] = deip_POW_APR_PERCENT;
    result["deip_PRODUCER_APR_PERCENT"] = deip_PRODUCER_APR_PERCENT;
    result["deip_PROXY_TO_SELF_ACCOUNT"] = deip_PROXY_TO_SELF_ACCOUNT;
    result["deip_RECENT_RSHARES_DECAY_RATE"] = deip_RECENT_RSHARES_DECAY_RATE;
    result["deip_REVERSE_AUCTION_WINDOW_SECONDS"] = deip_REVERSE_AUCTION_WINDOW_SECONDS;
    result["deip_ROOT_POST_PARENT"] = deip_ROOT_POST_PARENT;
    result["deip_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = deip_SAVINGS_WITHDRAW_REQUEST_LIMIT;
    result["deip_SAVINGS_WITHDRAW_TIME"] = deip_SAVINGS_WITHDRAW_TIME;
    result["deip_SOFT_MAX_COMMENT_DEPTH"] = deip_SOFT_MAX_COMMENT_DEPTH;
    result["deip_START_MINER_VOTING_BLOCK"] = deip_START_MINER_VOTING_BLOCK;
    result["deip_START_VESTING_BLOCK"] = deip_START_VESTING_BLOCK;
    result["deip_UPVOTE_LOCKOUT"] = deip_UPVOTE_LOCKOUT;
    result["deip_VESTING_FUND_PERCENT"] = deip_VESTING_FUND_PERCENT;
    result["deip_VESTING_WITHDRAW_INTERVALS"] = deip_VESTING_WITHDRAW_INTERVALS;
    result["deip_VESTING_WITHDRAW_INTERVALS_PRE_HF_16"] = deip_VESTING_WITHDRAW_INTERVALS_PRE_HF_16;
    result["deip_VESTING_WITHDRAW_INTERVAL_SECONDS"] = deip_VESTING_WITHDRAW_INTERVAL_SECONDS;
    result["deip_VOTE_DUST_THRESHOLD"] = deip_VOTE_DUST_THRESHOLD;
    result["deip_VOTE_REGENERATION_SECONDS"] = deip_VOTE_REGENERATION_SECONDS;
    result["deip_SYMBOL"] = deip_SYMBOL;
    result["VESTS_SYMBOL"] = VESTS_SYMBOL;
    result["VIRTUAL_SCHEDULE_LAP_LENGTH"] = VIRTUAL_SCHEDULE_LAP_LENGTH;
    result["deip_REWARDS_INITIAL_SUPPLY"] = deip_REWARDS_INITIAL_SUPPLY;
    result["deip_REWARDS_INITIAL_SUPPLY_PERIOD_IN_DAYS"] = deip_REWARDS_INITIAL_SUPPLY_PERIOD_IN_DAYS;
    result["deip_GUARANTED_REWARD_SUPPLY_PERIOD_IN_DAYS"] = deip_GUARANTED_REWARD_SUPPLY_PERIOD_IN_DAYS;
    result["deip_REWARD_INCREASE_THRESHOLD_IN_DAYS"] = deip_REWARD_INCREASE_THRESHOLD_IN_DAYS;
    result["deip_ADJUST_REWARD_PERCENT"] = deip_ADJUST_REWARD_PERCENT;
    result["deip_LIMIT_BUDGETS_PER_OWNER"] = deip_LIMIT_BUDGETS_PER_OWNER;
    result["deip_LIMIT_BUDGETS_LIST_SIZE"] = deip_LIMIT_BUDGETS_LIST_SIZE;
    result["deip_LIMIT_API_BUDGETS_LIST_SIZE"] = deip_LIMIT_API_BUDGETS_LIST_SIZE;

    return result;
}
} // namespace protocol
} // namespace deip
